version: "2"
run:
  modules-download-mode: readonly
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: all
  disable:
  - containedctx
  - cyclop
  - depguard
  - dupl
  - dupword
  - err113
  - exhaustruct
  - funlen
  - gocognit
  - goconst
  - gocyclo
  - interfacebloat
  - ireturn
  - lll
  - mnd
  - nestif
  - nilnil
  - nlreturn
  - varnamelen
  - wsl
  - wsl_v5
  settings:
    govet:
      enable-all: true
      disable:
      - fieldalignment
      settings:
        shadow:
          strict: true
    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true
    revive:
      enable-all-rules: true
      rules:
      - name: add-constant
        disabled: true
      - name: argument-limit
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: confusing-results
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: dot-imports
        arguments:
        - allowed-packages:
          - github.com/onsi/ginkgo/v2
          - github.com/onsi/gomega
      - name: flag-parameter
        disabled: true
      - name: function-length
        disabled: true
      - name: function-result-limit
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: nested-structs
        disabled: true
      - name: package-comments
        disabled: true
      - name: struct-tag
        arguments:
        - mapstructure,remain
        - yaml,remain
      - name: var-naming
        arguments:
        - []
        - []
        - [ skip-package-name-checks: true ]
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
          xml: snake
          bson: snake
          avro: snake
          header: snake
          mapstructure: snake
  exclusions:
    rules:
    - path: internal/cloudprovider/.+\.go
      linters:
      - gochecknoinits

formatters:
  enable:
  - gci
  - gofmt
  - gofumpt
  - goimports
  - golines
  - swaggo
  settings:
    gci:
      sections:
      - standard
      - default
      - localmodule
    gofumpt:
      extra-rules: true
    golines:
      max-len: 140
      shorten-comments: true
      reformat-tags: false
