#!/bin/sh
set -eu

cd "$(dirname "$0")"

if [ $# -eq 0 ]; then
  set -- run
fi

lint=./.lint.$(uname -s)

if [ ! -x "$lint" ] || [ go.mod -nt "$lint" ] || [ go.sum -nt "$lint" ]; then
	version=$(go list -m -f '{{.Version}}' github.com/golangci/golangci-lint/v2)
	date=$(date -u +%Y-%m-%dT%H:%M:%SZ)
	GOOS= go build -ldflags "-X main.version=$version -X main.commit=local -X main.date=$date" -o "$lint" github.com/golangci/golangci-lint/v2/cmd/golangci-lint
fi

export GOOS=linux

exec "$lint" "$@"
