version = 1
SPDX-PackageName = "Garden Linux GLCI"
SPDX-PackageSupplier = "Garden Linux authors <gardenlinux-admin@lists.neonephos.org>"
SPDX-PackageDownloadLocation = "https://github.com/gardenlinux/glci-next"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 SAP SE or an SAP affiliate company and Garden Linux contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 SAP SE or an SAP affiliate company and Garden Linux contributors"
SPDX-License-Identifier = "CC-BY-4.0"
