version = 1
SPDX-PackageName = "Gardenlinux glci"
SPDX-PackageSupplier = "GardenLinux authors <gardenlinux-admin@lists.neonephos.org>"
SPDX-PackageDownloadLocation = "https://github.com/gardenlinux/glci-next"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 SAP SE or an SAP affiliate company and Gardenlinux contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 SAP SE or an SAP affiliate company and Gardenlinux contributors"
SPDX-License-Identifier = "CC-BY-4.0"